apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    spec:
      containers:
      - name: loader
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache curl
          while true; do
            for i in $(seq 1 100); do
              curl -s http://flask-service/default/up &
            done
            wait
            sleep 1
          done
      restartPolicy: Never
  backoffLimit: 1
